coverage:
  status:
    project:
      default: off
      linux:
        flags: linux
        target: 98.0
        threshold: 0.1
        base: auto
      windows:
        flags: windows
        target: 96.9
        threshold: 0.1
        base: auto
