image: Visual Studio 2017

environment:
  matrix:
    #- TOXENV: py35
    #- TOXENV: py37-cover
    - TOXENV: integration
      ACME_SERVER: pebble-nonstrict
      PYTEST_ADDOPTS: -n4

branches:
  only:
    - master
    - /^\d+\.\d+\.x$/ # Version branches like X.X.X
    - /^test-.*$/

install:
  # Use Python 3.7 by default
  - SET PATH=C:\\Python37;C:\\Python37\\Scripts;%PATH%
  # Check env
  - python --version
  # Upgrade pip to avoid warnings
  - python -m pip install --upgrade pip
  # Ready to install tox and coverage
  - pip install tox codecov
  # Add necessary runtime dependencies
  - choco install nginx --params '"/noService"'

build: off

test_script:
  - set TOX_TESTENV_PASSENV=APPVEYOR
  # Test env is set by TOXENV env variable
  - tox

on_success:
  - if exist .coverage codecov
