install:
  - pip install wheel pytest pytest-xdist pyreadline
  - pip install -e .

build: off

test_script:
  - pytest --numprocesses auto --pyargs acme
  - pytest --numprocesses auto --pyargs certbot