branches:
  only:
    - master
    - /^\d+\.\d+\.x$/ # version branches like X.X.X
    - /^test-.*$/

install:
  - pip install wheel pytest pytest-xdist pyreadline
  - pip install -e .

build: off

test_script:
  - tox -c tox-win.ini