image: Visual Studio 2017

branches:
  only:
    - master
    - /^\d+\.\d+\.x$/ # version branches like X.X.X
    - /^test-.*$/

install:
  - pip install tox

build: off

test_script:
  - tox -c tox-win.ini
