image:
  # => Windows Server 2012 R2
  - Visual Studio 2015
  # => Windows Server 2016
  - Visual Studio 2017

branches:
  only:
    - master
    - /^\d+\.\d+\.x$/ # Version branches like X.X.X
    - /^test-.*$/

install:
  # Use Python 3.7 by default
  - "SET PATH=C:\\Python37;C:\\Python37\\Scripts;%PATH%"
  # Check env
  - "python --version"
  # Upgrade pip to avoid warnings
  - "python -m pip install --upgrade pip"
  # Ready to install tox and coverage
  - "pip install tox codecov"

build: off

test_script:
  # As it is the default python env, py37 is also tested by cover
  - tox -e py34,py35,cover

on_success:
  - codecov
