trigger:
- master

jobs:
  - job: linux
    pool:
      vmImage: ubuntu-latest
    strategy:
      matrix:
        py27-cover:
          PYTHON_VERSION: 2.7
          TOXENV: py35
        py34:
          PYTHON_VERSION: 3.4
          TOXENV: py34
        py37:
          PYTHON_VERSION: 3.7
          TOXENV: py37
        integration-certbot:
          PYTHON_VERSION: 2.7
          TOXENV: integration
          PYTEST_ADDOPTS: --numprocesses 4
        pylint:
          PYTHON_VERSION: 2.7
          TOXENV: lint
        mypy:
          PYTHON_VERSION: 3.5
          TOXENV: mypy
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
          addToPath: true
      - script: |
          sudo letsencrypt-auto-source/letsencrypt-auto -n --os-packages-only
          sudo apt install -y --no-install-recommends nginx-light
        condition: eq(variables['Agent.OS'], 'Linux')
        displayName: Install OS packages
      - script: python tools/pip_install.py tox codecov
        displayName: Install tools
      - script: python -m tox
        displayName: 'Run tox'

  - job: windows
    pool:
      vmImage: windows-latest
    strategy:
      matrix:
        windows-py35:
          PYTHON_VERSION: 3.5
          TOXENV: py35
        windows-py37-cover:
          PYTHON_VERSION: 3.7
          TOXENV: py37-cover
        windows-integration-certbot:
          PYTHON_VERSION: 3.7
          TOXENV: integration-certbot
          PYTEST_ADDOPTS: --numprocesses 4
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
          addToPath: true
      - script: python tools/pip_install.py tox codecov
        displayName: Install dependencies
      - script: python -m tox
        displayName: 'Run tox'
