trigger:
- master

jobs:
  - job: linux
    pool:
      vmImage: ubuntu-latest
    strategy:
      matrix:
        integration-certbot:
          PYTHON_VERSION: 2.7
          TOXENV: integration
          PYTEST_ADDOPTS: --numprocesses 4
        py27-cover:
          PYTHON_VERSION: 2.7
          TOXENV: py35
        pylint:
          PYTHON_VERSION: 2.7
          TOXENV: lint
        py34-mypy:
          PYTHON_VERSION: 3.4
          TOXENV: mypy
        py35-mypy:
          PYTHON_VERSION: 3.5
          TOXENV: mypy
        py34:
          PYTHON_VERSION: 3.4
          TOXENV: py34
        py37:
          PYTHON_VERSION: 3.7
          TOXENV: py37
        apache-compat:
          PYTHON_VERSION: 2.7
          TOXENV: apache_compat
        le-auto-xenial:
          PYTHON_VERSION: 2.7
          TOXENV: le_auto_xenial
        apacheconftest:
          PYTHON_VERSION: 2.7
          TOXENV: apacheconftest-with-pebble
        nginxroundtrip:
          PYTHON_VERSION: 2.7
          TOXENV: nginxroundtrip
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
          addToPath: true
      - script: |
          sudo letsencrypt-auto-source/letsencrypt-auto -n --os-packages-only
          sudo apt install -y --no-install-recommends nginx-light
        displayName: Install OS packages
      - script: python tools/pip_install.py tox codecov
        displayName: Install tools
      - script: python -m tox
        displayName: 'Run tox'

  - job: windows
    pool:
      vmImage: windows-latest
    strategy:
      matrix:
        py35:
          PYTHON_VERSION: 3.5
          TOXENV: py35
        py37-cover:
          PYTHON_VERSION: 3.7
          TOXENV: py37-cover
        integration-certbot:
          PYTHON_VERSION: 3.7
          TOXENV: integration-certbot
          PYTEST_ADDOPTS: --numprocesses 4
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
          addToPath: true
      - script: python tools/pip_install.py tox codecov
        displayName: Install dependencies
      - script: python -m tox
        displayName: 'Run tox'

  - job: oldest_linux
    pool:
      vmImage: ubuntu-latest
    container: ubuntu:trusty
    variables:
      TOXENV: py27-{acme,apache,certbot,dns,nginx}-oldest
      TRAVIS_BUILD_DIR: dummy
      TRAVIS_BRANCH: dummy
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 2.7
          addToPath: true
      - script: |
          sudo letsencrypt-auto-source/letsencrypt-auto -n --os-packages-only
          sudo apt install -y --no-install-recommends python-tox
        displayName: Install OS packages
      - script: tox
        displayName: 'Run tox'
