version: 2

dependencies: &install_dependencies
  command: |
    pip install --upgrade tox
  name: Install required runtime dependencies

shared: &shared
  steps:
    - run:
        <<: *install_dependencies
    - checkout
    - run:
        name: Execute tox target
        command: tox

jobs:
  "python-2.7-lint":
    <<: *shared
    docker:
      - image: python:2.7-slim
    environment:
      TOXENV: lint
  "python-2.7-cover":
    <<: *shared
    docker:
    - image: python:2.7-slim
    environment:
      TOXENV: py27-cover
  "python-2.7-oldest":
    <<: *shared
    docker:
    - image: python:2.7-slim
    environment:
      TOXENV: py27-{acme,apache,certbot,dns,nginx,postfix}-oldest
  "python-3.4-mypy":
    <<: *shared
    docker:
      - image: python:3.4-slim
    environment:
      TOXENV: mypy
  "python-3.5-mypy":
    <<: *shared
    docker:
    - image: python:3.4-slim
    environment:
      TOXENV: mypy
  "python-3.4-tests":
    <<: *shared
    docker:
      - image: python:3.4-slim
    environment:
      TOXENV: py34
  "python-3.7-tests":
    <<: *shared
    docker:
      - image: python:3.7-slim
    environment:
      TOXENV: py37

workflows:
  version: 2
  build:
    jobs:
      - "python-2.7-lint"
      - "python-2.7-cover"
      - "python-2.7-oldest"
      - "python-3.4-mypy"
      - "python-3.5-mypy"
      - "python-3.4-tests"
      - "python-3.7-tests"
