version: 2

jobs:
  "jessie":
    docker:
    - image: debian:jessie
    environment:
      TOXENV: py27-{acme,apache,certbot,dns,nginx,postfix}-oldest
    steps:
      - checkout
      - run:
          command: |
            ./certbot-auto --os-packages-only --non-interactive
            apt-get update && apt-get install -y curl git
            curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
            python get-pip.py
            pip install tox
          name: Install required runtime dependencies
      - run:
          name: Execute tox target
          command: tox
  "xenial":
    docker:
    - image: ubuntu:xenial
    environment:
      TOXENV: py27-{acme,apache,certbot,dns,nginx,postfix}-oldest
    steps:
      - checkout
      - run:
          command: |
            ./certbot-auto --os-packages-only --non-interactive
            apt-get update && apt-get install -y curl git
            curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
            python get-pip.py
            pip install tox
          name: Install required runtime dependencies
      - run:
          name: Execute tox target
          command: tox
  "centos7":
    docker:
    - image: centos:7
    environment:
      TOXENV: py27-{acme,apache,certbot,dns,nginx,postfix}-oldest
    steps:
      - checkout
      - run:
          command: |
            ./certbot-auto --os-packages-only --non-interactive
            yum install -y curl git
            curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
            python get-pip.py
            pip install tox
          name: Install required runtime dependencies
      - run:
          name: Execute tox target
          command: tox
  "centos6":
    docker:
    - image: centos:6
    environment:
      TOXENV: py27-{acme,apache,certbot,dns,nginx,postfix}-oldest
    steps:
      - checkout
      - run:
          command: |
            yum install -y centos-release-SCL
            yum install -y python27
            source /opt/rh/python27/enable
            ./certbot-auto --os-packages-only --non-interactive
            yum install -y curl git
            curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
            python get-pip.py
            pip install tox
          name: Install required runtime dependencies
      - run:
          name: Execute tox target
          command: |
            source /opt/rh/python27/enable
            tox

workflows:
  version: 2
  build:
    jobs:
      - jessie
      - xenial
      - centos7
      - centos6
