schedules:
- cron: "0 0 * * *"
  displayName: Nightly build
  branches:
    include:
    - master

jobs:
  - template: templates/standard.yml

  - job: installer
    pool:
      vmImage: windows-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.7
        architecture: x86
        addToPath: true
    - script: python windows-installer/construct.py
      displayName: Build Certbot installer
    - script: python windows-installer/install.py
      displayName: Run Certbot installer
    - script: |
        echo "##vso[task.prependpath]%LOCALAPPDATA%\Certbot\bin"
      displayName: Update PATH
    - script: certbot --version
      displayName: Check Certbot availability
