schedules:
- cron: "0 0 * * *"
  displayName: Nightly build
  branches:
    include:
    - master

jobs:
  - template: templates/standard.yml

  - job: installer
    pool:
      vmImage: windows-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.7
        addToPath: true
    - script: windows-installer/construct.py
      displayName: Install NSIS
    - script: (build/certbot-*-installer-*.exe) /SD
      displayName: Run Certbot installer
    - script: certbot --version
      displayName: Check certbot availability
