name: main

on:
  push:
    branches: [master-github]
  pull_request:
    branches: [master-github, "*.x"]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: ["3.7"]
        toxenv: [py37]
        include:
          - os: ubuntu-18.04
            python-version: "3.10"
            toxenv: py310
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare environment
        uses: ./.github/actions/setup-test-env
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tox
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: |
          python -m tox
